# Reference:- TS 29.531 R16.0.0., Section- 6.1.6 Data Model 
info:
  version: 1.4.0
  description: OAI-NSSF Release v1.4.0
configuration:
  nsiInfoList:
    - snssai:
        sst: 1
      nsiInformationList:
        nrfId: http://oai-nrf:80/nnrf-disc/v1/nf-instances
        nsiId: '11'
    - snssai:
        sst: 2
      nsiInformationList:
        nrfId: http://oai-nrf:80/nnrf-disc/v1/nf-instances
        nsiId: '12'
    - snssai:
        sst: 3
      nsiInformationList:
        nrfId: http://oai-nrf2:80/nnrf-disc/v1/nf-instances
        nsiId: '12'
  taInfoList:
    - tai:
        plmnId:
          mcc: '208'
          mnc: '95'
        tac: '0x0001'
      supportedSnssaiList:
      - sst: 1
      - sst: 2
      - sst: 3
  amfInfoList:
    - targetAmfSet: oai5gcn.mcc208.mnc95.regionid128.setid1.3gppnetwork.org
      nrfAmfSet: http://oai-cn5g-nrf.fr:8080/nnrf-disc/v1/nf-instances
      nrfAmfSetNfMgtUri: http://oai-cn5g-nrf.fr:8080/nnrf-nfm/v1/nf-instances
      amfList:
        - nfId: 405e8251-cc5a-45dd-a494-efb9eaf1cd58
          supportedNssaiAvailabilityData:
              tai:
                plmnId:
                  mcc: 208
                  mnc: 95
                tac: 0x0001
              supportedSnssaiList:
                - sst: 1
                - sst: 2
                - sst: 3
